service: python

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  timeout: 600

package:
  individually: true

functions:
  originalCode:
    handler: src/originalCode.lambda_handler
    memorySize: 512
  updatedCode:
    handler: src/updatedCode.lambda_handler
    memorySize: 512
  updatedCode2:
    handler: src/updatedCode2.lambda_handler
    memorySize: 512

  binaryTree:
    handler: src/betterBenchmarks/binaryTree1.lambda_handler
    memorySize: 512
